(() => {
  'use strict';

  const KEY = 'bda-v3-tournaments';
  const seeds = [
    {id:'copa-grifo',name:'Copa Grifo BDA',edition:'8ª edição',format:'Mata-mata',status:'Finalizado',phase:'Campeão definido',maxTeams:19,badge:'🦅',participants:['Zombie FC BDA','JOGOBUGADO BDA','Inter Brasil BDA','Vasco da Gama BDA'],description:'Competição tradicional do Clã BDA em formato eliminatório e jogo único.',legacy:true,locked:true},
    {id:'copa-francos',name:'Copa Francos',edition:'Próxima edição',format:'Mata-mata',status:'Planejado',phase:'Preparação',maxTeams:16,badge:'🕊️',participants:[],description:'Competição especial em homenagem à história do Francos FC BDA.'},
    {id:'supercopa',name:'SuperCopa BDA',edition:'Temporada atual',format:'Mata-mata',status:'Em andamento',phase:'Semifinais',maxTeams:4,badge:'⚡',participants:['São Paulo BDA','Flamestre BDA','CR Flamengo BDA','CV Cruz BDA'],description:'Confronto entre grandes campeões das ligas e copas do Clã BDA.'},
    {id:'liga-a',name:'Liga A BDA',edition:'Temporada encerrada',format:'Pontos corridos',status:'Finalizado',phase:'Campeão: Inter Brasil BDA',maxTeams:20,badge:'🥇',participants:['Inter Brasil BDA'],description:'A divisão de elite do Clã BDA.'},
    {id:'liga-b',name:'Liga B BDA',edition:'Temporada encerrada',format:'Pontos corridos',status:'Finalizado',phase:'Campeão: Vasco da Gama BDA',maxTeams:20,badge:'🛡️',participants:['Vasco da Gama BDA'],description:'A divisão de acesso para a Liga A BDA.'}
  ];

  const page = document.querySelector('[data-page="tournament"]');
  if (!page) return;

  const oldBracket = page.innerHTML;
  let tournaments = load();
  let selectedId = tournaments[0]?.id || '';
  let editingId = null;
  let pendingBanner = '';
  let filter = 'Todos';

  const style = document.createElement('style');
  style.textContent = `
    .arena-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}
    .arena-card{overflow:hidden;padding:0;min-height:218px;text-align:left}
    .arena-cover{position:relative;height:116px;overflow:hidden;background:radial-gradient(circle at 75% 18%,rgba(242,215,125,.38),transparent 25%),linear-gradient(145deg,#183a26,#08110c)}
    .arena-cover img{width:100%;height:100%;display:block;object-fit:cover}
    .arena-cover:after{content:"";position:absolute;inset:auto 0 0;height:60%;background:linear-gradient(transparent,rgba(5,10,8,.9))}
    .arena-symbol{position:absolute;right:11px;top:8px;z-index:2;font-size:48px;filter:drop-shadow(0 8px 14px #0008)}
    .arena-status{position:absolute;left:9px;top:9px;z-index:2;padding:6px 8px;border:1px solid #ffffff2b;border-radius:999px;color:#fff;background:#050a08b8;font-size:8px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}
    .arena-body{padding:13px}.arena-body h3{margin:5px 0 0;font-size:22px;line-height:.95;text-transform:uppercase}
    .arena-edition{color:var(--gold-soft);font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.11em}
    .arena-meta{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:11px}.arena-meta span{padding:7px;border:1px solid var(--line);border-radius:10px;color:var(--muted);font-size:9px}
    .arena-open{width:100%;min-height:37px;margin-top:9px}
    .arena-toolbar{display:flex;gap:7px;overflow-x:auto;margin:0 0 13px;padding-bottom:5px;scrollbar-width:none}.arena-toolbar::-webkit-scrollbar{display:none}
    .arena-filter{min-height:35px;padding:0 12px;white-space:nowrap;border:1px solid var(--line);border-radius:999px;color:var(--muted);background:#ffffff08;font-size:9px;font-weight:800;text-transform:uppercase}
    .arena-filter.active{color:#171107;border-color:var(--gold);background:linear-gradient(135deg,var(--gold-soft),var(--gold))}
    .arena-detail{margin-top:18px}.arena-hero{position:relative;overflow:hidden;min-height:245px;display:grid;align-content:end;padding:20px;border:1px solid var(--line-strong);border-radius:25px;background:radial-gradient(circle at 82% 18%,rgba(242,215,125,.36),transparent 24%),linear-gradient(145deg,#173b26,#08110c);box-shadow:var(--shadow)}
    .arena-hero>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.arena-hero:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,#0000,#030806ee)}
    .arena-hero-copy{position:relative;z-index:2}.arena-hero-copy h2{margin:7px 0 6px;font-size:clamp(34px,8vw,58px);line-height:.88;text-transform:uppercase}.arena-hero-copy p{margin:0;color:#d8e1db;font-size:12px;line-height:1.55}
    .arena-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:13px}.arena-stats{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:10px}.arena-stat{padding:13px;border:1px solid var(--line);border-radius:15px;background:linear-gradient(150deg,var(--surface-2),var(--surface))}.arena-stat b{display:block;color:var(--gold-soft);font:800 18px "Barlow Condensed",sans-serif;text-transform:uppercase}.arena-stat span{color:var(--muted);font-size:8px;text-transform:uppercase}
    .arena-clubs{display:flex;flex-wrap:wrap;gap:7px}.arena-club{padding:8px 10px;border:1px solid var(--line);border-radius:999px;color:#dce6df;background:#ffffff08;font-size:10px}
    .arena-placeholder{margin-top:12px;padding:23px 15px;border:1px dashed var(--line-strong);border-radius:18px;color:var(--muted);text-align:center;font-size:11px;line-height:1.55}.arena-legacy{margin-top:17px;border-top:1px solid var(--line)}
    .arena-home-scroll{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(210px,72%);gap:10px;overflow-x:auto;padding:2px 2px 8px}.arena-home-card{position:relative;overflow:hidden;min-height:140px;padding:14px;display:grid;align-content:end}.arena-home-card:before{content:attr(data-icon);position:absolute;right:8px;top:3px;font-size:62px;opacity:.18}.arena-home-card h3{position:relative;margin:5px 0;font-size:23px;text-transform:uppercase}.arena-home-card p,.arena-home-card button,.arena-home-card .eyebrow{position:relative}.arena-home-card p{margin:0;color:var(--muted);font-size:10px}.arena-home-card button{justify-self:start;min-height:34px;margin-top:9px;padding:0 11px;font-size:10px}
    .arena-team-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;max-height:185px;overflow:auto;padding:8px;border:1px solid var(--line);border-radius:13px;background:#03080670}.arena-team-option{display:flex;align-items:center;gap:7px;padding:8px;border:1px solid var(--line);border-radius:9px;color:#dce6df;background:#ffffff08;font-size:9px;text-transform:none;letter-spacing:0}.arena-team-option input{width:auto;margin:0}
    .arena-banner-preview{margin-top:8px;overflow:hidden;border:1px solid var(--line);border-radius:14px;background:#07100c}.arena-banner-preview div{aspect-ratio:16/9;display:grid;place-items:center;color:var(--muted);font-size:10px}.arena-banner-preview img{width:100%;height:100%;object-fit:cover}.arena-banner-preview span{display:block;padding:8px 10px;color:var(--muted);font-size:9px;text-transform:none;letter-spacing:0}
    @media(min-width:760px){.arena-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.arena-stats{grid-template-columns:repeat(4,1fr)}.arena-home-scroll{grid-auto-columns:minmax(235px,31%)}.arena-team-options{grid-template-columns:repeat(3,minmax(0,1fr))}}
  `;
  document.head.appendChild(style);

  function copy(value){return JSON.parse(JSON.stringify(value))}
  function load(){try{const value=JSON.parse(localStorage.getItem(KEY));if(!Array.isArray(value)||!value.length)return copy(seeds);const normalized=value.filter(item=>String(item?.id)!=='copa-aguia'&&!/copa\s+águia/i.test(String(item?.name||'')));if(normalized.length!==value.length)localStorage.setItem(KEY,JSON.stringify(normalized));return normalized}catch{return copy(seeds)}}
  function persist(previous){try{localStorage.setItem(KEY,JSON.stringify(tournaments));return true}catch{if(previous)tournaments=previous;toast('Não foi possível salvar os campeonatos');return false}}
  function safe(value){return String(value||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')}
  function slug(value){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`campeonato-${Date.now()}`}
  function fileData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Falha ao ler a imagem'));reader.readAsDataURL(file)})}
  function imageFrom(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Imagem inválida'));image.src=src})}
  async function prepareBanner(file){if(!file.type.startsWith('image/'))throw new Error('Escolha uma imagem válida');if(file.size>8*1024*1024)throw new Error('O banner deve ter no máximo 8 MB');const src=await fileData(file);const image=await imageFrom(src);const scale=Math.min(1,1200/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Falha ao processar a imagem');ctx.drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/webp',.84)}

  function list(){if(filter==='Todos')return tournaments;if(filter==='Abertos')return tournaments.filter(t=>['Inscrições abertas','Em andamento'].includes(t.status));return tournaments.filter(t=>t.status===filter)}
  function card(t){const clubs=Array.isArray(t.participants)?t.participants.length:0,max=Number(t.maxTeams)||0,occupancy=max?Math.min(100,Math.round(clubs/max*100)):0;return `<article class="card arena-card" data-state="${safe(slug(t.status||'planejado'))}"><div class="arena-cover">${t.banner?`<img src="${safe(t.banner)}" alt="Banner de ${escapeHtml(t.name)}">`:''}<span class="arena-status">${escapeHtml(t.status)}</span><span class="arena-symbol">${escapeHtml(t.badge||'🏆')}</span><span class="arena-cover-edition">${escapeHtml(t.edition||'Nova edição')}</span></div><div class="arena-body"><h3>${escapeHtml(t.name)}</h3><p>${escapeHtml(t.description||'Campeonato oficial do Clã BDA.')}</p><div class="arena-meta"><span><b>${escapeHtml(t.format||'A definir')}</b> formato</span><span><b>${clubs}/${max||'∞'}</b> clubes</span></div><div class="arena-capacity"><span style="width:${occupancy}%"></span></div><button class="ghost arena-open" type="button" data-open-tournament="${escapeHtml(t.id)}">Ver competição <b>→</b></button></div></article>`}
  function renderCards(){const grid=document.getElementById('arenaGrid');if(!grid)return;const items=list();grid.innerHTML=items.length?items.map(card).join(''):'<div class="empty" style="grid-column:1/-1">Nenhum campeonato neste filtro.</div>'}
  function renderFilters(){document.querySelectorAll('[data-arena-filter]').forEach(btn=>btn.classList.toggle('active',btn.dataset.arenaFilter===filter))}
  function renderDetail(){const root=document.getElementById('arenaDetail');if(!root)return;const t=tournaments.find(item=>item.id===selectedId)||tournaments[0];if(!t){root.innerHTML='<div class="empty">Crie o primeiro campeonato.</div>';return}selectedId=t.id;const clubs=Array.isArray(t.participants)?t.participants:[];root.innerHTML=`<div class="arena-detail-nav"><span>${escapeHtml(t.badge||'🏆')} ${escapeHtml(t.name)}</span><nav><button type="button" data-tournament-jump="overview">Visão geral</button><button type="button" data-tournament-jump="competition">Competição</button><button type="button" data-tournament-jump="clubs">Clubes</button></nav></div><div class="arena-hero" id="tournamentOverview">${t.banner?`<img src="${safe(t.banner)}" alt="Banner de ${escapeHtml(t.name)}">`:''}<div class="arena-hero-copy"><div class="arena-hero-labels"><span>${escapeHtml(t.status)}</span><span>${escapeHtml(t.edition||'Nova edição')}</span></div><span class="arena-hero-symbol">${escapeHtml(t.badge||'🏆')}</span><h2>${escapeHtml(t.name)}</h2><p>${escapeHtml(t.description||'Campeonato oficial do Clã BDA.')}</p>${isAdmin?`<div class="arena-actions"><button class="secondary" type="button" data-edit-tournament="${escapeHtml(t.id)}">Editar campeonato</button>${t.locked?'':`<button class="danger" type="button" data-delete-tournament="${escapeHtml(t.id)}">Excluir campeonato</button>`}</div>`:''}</div></div><div class="arena-stats"><div class="arena-stat"><span>Formato</span><b>${escapeHtml(t.format||'A definir')}</b></div><div class="arena-stat"><span>Fase atual</span><b>${escapeHtml(t.phase||'Preparação')}</b></div><div class="arena-stat"><span>Participantes</span><b>${clubs.length}<small> / ${Number(t.maxTeams)||'∞'}</small></b></div><div class="arena-stat"><span>Situação</span><b>${escapeHtml(t.status||'Planejado')}</b></div></div><section class="arena-club-section" id="tournamentClubs"><div class="section-head"><div><span class="eyebrow">Elenco da competição</span><h2>Clubes participantes</h2><p>${clubs.length} times confirmados nesta edição</p></div></div>${clubs.length?`<div class="arena-clubs">${clubs.map((name,index)=>`<span class="arena-club"><i>${index+1}</i>${escapeHtml(name)}</span>`).join('')}</div>`:'<div class="arena-placeholder">Nenhum clube selecionado. Edite o campeonato para escolher os participantes.</div>'}</section><section id="tournamentCompetition">${t.legacy?`<div class="arena-legacy">${oldBracket}</div>`:'<div class="arena-placeholder">Área preparada para chaveamento, tabela e resultados desta competição.</div>'}</section>`}
  function renderAll(){renderFilters();renderCards();renderDetail();renderHome();updateStats()}

  function buildPage(){page.innerHTML=`<section class="arena-page-hero"><div><span class="eyebrow">Central oficial de competições</span><h1>Campeonatos BDA</h1><p>Copas, ligas, resultados e chaveamentos organizados em uma única arena.</p></div><aside><b>${tournaments.length}</b><span>competições registradas</span><button class="primary" id="createTournamentBtn" type="button" hidden>+ Criar campeonato</button></aside></section><div class="arena-catalog-head"><div><span class="eyebrow">Escolha uma competição</span><h2>Temporadas da Arena</h2></div><div class="arena-toolbar"><button class="arena-filter active" type="button" data-arena-filter="Todos">Todos</button><button class="arena-filter" type="button" data-arena-filter="Abertos">Abertos</button><button class="arena-filter" type="button" data-arena-filter="Planejado">Planejados</button><button class="arena-filter" type="button" data-arena-filter="Finalizado">Finalizados</button></div></div><div class="arena-grid" id="arenaGrid"></div><div class="arena-detail" id="arenaDetail"></div>`}
  function buildModal(){const modal=document.createElement('div');modal.className='modal-backdrop';modal.id='tournamentModal';modal.innerHTML=`<div class="modal"><h2 id="tournamentModalTitle">Criar campeonato</h2><p>Monte uma copa ou liga para o Clã BDA.</p><form id="tournamentForm"><div class="form-grid two"><label>Nome<input id="tName" required maxlength="55" placeholder="Copa dos Campeões BDA"></label><label>Edição<input id="tEdition" maxlength="35" placeholder="1ª edição"></label><label>Formato<select id="tFormat"><option>Mata-mata</option><option>Pontos corridos</option><option>Grupos + mata-mata</option><option>Turno e returno</option></select></label><label>Limite de times<input id="tMax" type="number" min="2" max="64" value="16"></label><label>Status<select id="tStatus"><option>Planejado</option><option>Inscrições abertas</option><option>Em andamento</option><option>Finalizado</option></select></label><label>Fase atual<input id="tPhase" maxlength="45" placeholder="Inscrições"></label><label>Símbolo<input id="tBadge" maxlength="4" placeholder="🏆"></label><label>Prazo<input id="tDeadline" maxlength="45" placeholder="24h por fase"></label><label style="grid-column:1/-1">Descrição<textarea id="tDescription" maxlength="260"></textarea></label><label style="grid-column:1/-1">Banner<input id="tBanner" type="file" accept="image/png,image/jpeg,image/webp"><div class="arena-banner-preview" id="tBannerPreview"></div></label><div style="grid-column:1/-1"><label>Clubes participantes</label><div class="arena-team-options" id="tTeams"></div></div></div><div class="form-actions"><button type="button" class="secondary" data-close="tournamentModal">Cancelar</button><button class="primary" type="submit">Salvar</button></div></form></div>`;document.body.appendChild(modal)}

  function preview(current=''){const root=document.getElementById('tBannerPreview');if(!root)return;const image=pendingBanner||current;root.innerHTML=image?`<div><img src="${safe(image)}" alt="Prévia do banner"></div><span>O banner aparecerá no cartão e na página do campeonato.</span>`:'<div>Prévia do banner</div><span>Imagens horizontais em 16:9 ficam melhores.</span>'}
  function teamOptions(selected=[]){const root=document.getElementById('tTeams');if(!root)return;root.innerHTML=Array.isArray(teams)&&teams.length?teams.map((team,index)=>`<label class="arena-team-option"><input type="checkbox" name="arenaTeams" value="${index}" ${selected.includes(team.name)?'checked':''}><span>${escapeHtml(team.name)}</span></label>`).join(''):'<span style="color:var(--muted);font-size:10px">Cadastre clubes na aba Times.</span>'}
  function openEditor(id=null){if(!isAdmin)return;editingId=id;pendingBanner='';const form=document.getElementById('tournamentForm');form.reset();const t=tournaments.find(item=>item.id===id);document.getElementById('tournamentModalTitle').textContent=t?'Editar campeonato':'Criar campeonato';if(t){tName.value=t.name||'';tEdition.value=t.edition||'';tFormat.value=t.format||'Mata-mata';tMax.value=Number(t.maxTeams)||16;tStatus.value=t.status||'Planejado';tPhase.value=t.phase||'';tBadge.value=t.badge||'';tDeadline.value=t.deadline||'';tDescription.value=t.description||''}teamOptions(t?.participants||[]);preview(t?.banner||'');openModal('tournamentModal');tName.focus()}
  function chosenTeams(){return Array.from(document.querySelectorAll('input[name="arenaTeams"]:checked')).map(input=>teams[Number(input.value)]?.name).filter(Boolean)}
  function submitTournament(event){event.preventDefault();if(!isAdmin)return;const name=tName.value.trim();if(!name)return;const before=copy(tournaments);const old=tournaments.find(item=>item.id===editingId);const item={...(old||{}),id:old?.id||`${slug(name)}-${Date.now().toString(36)}`,name,edition:tEdition.value.trim()||'Nova edição',format:tFormat.value,maxTeams:Number(tMax.value)||16,status:tStatus.value,phase:tPhase.value.trim()||'Preparação',badge:tBadge.value.trim()||'🏆',deadline:tDeadline.value.trim(),description:tDescription.value.trim()||'Campeonato oficial do Clã BDA.',participants:chosenTeams()};if(pendingBanner)item.banner=pendingBanner;if(old)tournaments[tournaments.findIndex(t=>t.id===old.id)]=item;else tournaments.unshift(item);if(!persist(before))return;selectedId=item.id;editingId=null;pendingBanner='';event.target.reset();closeModal('tournamentModal');renderAll();toast(old?'Campeonato atualizado':'Campeonato criado')}
  function removeTournament(id){if(!isAdmin)return;const item=tournaments.find(t=>t.id===id);if(!item||item.locked||!confirm(`Excluir ${item.name}?`))return;const before=copy(tournaments);tournaments=tournaments.filter(t=>t.id!==id);selectedId=tournaments[0]?.id||'';if(!persist(before))return;renderAll();toast('Campeonato excluído')}

  function branding(){document.title='Arena BDA | Campeonatos do Clã';const name=document.querySelector('.brand-copy strong');const sub=document.querySelector('.brand-copy span');if(name)name.textContent='Arena BDA';if(sub)sub.textContent='Competições oficiais • Clã BDA';const hero=document.querySelector('[data-page="home"] .hero');if(hero){hero.querySelector('.eyebrow').textContent='Temporada BDA • Central oficial';hero.querySelector('h1').textContent='A casa dos campeonatos BDA.';hero.querySelector('p').textContent='Acompanhe partidas, classificações, chaveamentos e a história competitiva do clã em tempo real.';const buttons=hero.querySelectorAll('.hero-actions button');if(buttons[0])buttons[0].textContent='Abrir campeonatos';if(buttons[1])buttons[1].textContent='Explorar clubes'}const stats=document.querySelector('[data-page="home"] .quick-stats');if(stats)stats.id='arenaStats';const nav=document.querySelector('.nav-btn[data-go="tournament"] span');if(nav)nav.textContent='Campeonatos';const ch=document.querySelector('[data-page="champions"] h2');if(ch)ch.textContent='Sala de Troféus BDA';const tp=document.querySelector('[data-page="teams"] .section-head h2');if(tp)tp.textContent='Clubes BDA';const admin=document.getElementById('adminPanel');if(admin){admin.querySelector('h3').textContent='Central administrativa Arena BDA';admin.querySelector('p').textContent='Gerencie campeonatos, clubes e a Sala de Troféus. As alterações ainda são salvas neste navegador.';const tools=admin.querySelector('.admin-tools');const btn=document.createElement('button');btn.className='primary';btn.id='adminCreateTournamentBtn';btn.type='button';btn.textContent='Criar campeonato';tools.prepend(btn)}}
  function updateStats(){const root=document.getElementById('arenaStats');if(!root)return;const active=tournaments.filter(t=>t.status==='Em andamento').length;const open=tournaments.filter(t=>t.status==='Inscrições abertas').length;root.innerHTML=`<div class="stat"><b>${tournaments.length}</b><span>Campeonatos</span></div><div class="stat"><b>${active}</b><span>Em andamento</span></div><div class="stat"><b>${open}</b><span>Inscrições</span></div><div class="stat"><b>${teams.length}</b><span>Clubes</span></div><div class="stat"><b>${champions.length}</b><span>Campeões</span></div><div class="stat"><b>BDA</b><span>Uma só arena</span></div>`}
  function buildHome(){const home=document.querySelector('[data-page="home"]');const grid=home?.querySelector('.home-grid');if(!grid)return;const command=document.createElement('section');command.className='home-command';command.innerHTML=`<header><div><span class="eyebrow">Acesso rápido</span><h2>O que você quer acompanhar?</h2></div><span class="home-online"><i></i>Arena online</span></header><nav><button type="button" data-go="tournament"><i>🏆</i><span><b>Campeonatos</b><small>Jogos e chaveamentos</small></span><em>→</em></button><button type="button" data-go="registrations"><i>✍️</i><span><b>Inscrições</b><small>Entre nas competições</small></span><em>→</em></button><button type="button" data-go="ranking"><i>📊</i><span><b>Ranking BDA</b><small>Classificação geral</small></span><em>→</em></button><button type="button" data-go="news"><i>📰</i><span><b>Notícias</b><small>Comunicados oficiais</small></span><em>→</em></button></nav>`;const section=document.createElement('section');section.className='home-tournaments';section.innerHTML=`<div class="section-head"><div><span class="eyebrow">Temporadas em evidência</span><h2>Campeonatos em destaque</h2><p>As principais competições da Arena BDA</p></div><button data-go="tournament">Ver catálogo completo</button></div><div class="arena-home-scroll" id="arenaHome"></div>`;grid.before(command,section)}
  function renderHome(){const root=document.getElementById('arenaHome');if(!root)return;root.innerHTML=tournaments.slice(0,5).map(t=>`<article class="card arena-home-card" data-icon="${escapeHtml(t.badge||'🏆')}"><span class="eyebrow">${escapeHtml(t.status)}</span><h3>${escapeHtml(t.name)}</h3><p>${escapeHtml(t.edition||t.phase)}</p><button class="ghost" type="button" data-home-tournament="${escapeHtml(t.id)}">Ver campeonato</button></article>`).join('')}

  buildPage();buildModal();branding();buildHome();
  const oldRenderTeams=renderTeams;renderTeams=function(){oldRenderTeams();updateStats()};
  const oldRenderChampions=renderChampions;renderChampions=function(){oldRenderChampions();updateStats()};
  const oldAdminUI=updateAdminUI;updateAdminUI=function(){oldAdminUI();const create=document.getElementById('createTournamentBtn');if(create)create.hidden=!isAdmin;const adminCreate=document.getElementById('adminCreateTournamentBtn');if(adminCreate)adminCreate.hidden=!isAdmin;renderDetail()};

  document.getElementById('tBanner').addEventListener('change',async event=>{const file=event.target.files?.[0];const current=tournaments.find(t=>t.id===editingId)?.banner||'';if(!file){pendingBanner='';preview(current);return}try{toast('Preparando o banner...');pendingBanner=await prepareBanner(file);preview(current);toast('Banner carregado')}catch(error){pendingBanner='';event.target.value='';preview(current);toast(error.message||'Falha ao carregar o banner')}});
  document.getElementById('tournamentForm').addEventListener('submit',submitTournament);
  document.getElementById('createTournamentBtn').addEventListener('click',()=>openEditor());
  document.getElementById('adminCreateTournamentBtn').addEventListener('click',()=>openEditor());
  document.addEventListener('click',event=>{const f=event.target.closest('[data-arena-filter]');if(f){filter=f.dataset.arenaFilter;renderFilters();renderCards();return}const open=event.target.closest('[data-open-tournament]');if(open){selectedId=open.dataset.openTournament;renderDetail();document.getElementById('arenaDetail')?.scrollIntoView({behavior:'smooth'});return}const home=event.target.closest('[data-home-tournament]');if(home){selectedId=home.dataset.homeTournament;navigate('tournament');renderAll();return}const edit=event.target.closest('[data-edit-tournament]');if(edit){openEditor(edit.dataset.editTournament);return}const del=event.target.closest('[data-delete-tournament]');if(del)removeTournament(del.dataset.deleteTournament)});
  document.addEventListener('click',event=>{const jump=event.target.closest('[data-tournament-jump]');if(!jump)return;const targets={overview:'tournamentOverview',competition:'tournamentCompetition',clubs:'tournamentClubs'};document.getElementById(targets[jump.dataset.tournamentJump])?.scrollIntoView({behavior:'smooth',block:'start'})});
  document.getElementById('resetDemoBtn')?.addEventListener('click',()=>{tournaments=copy(seeds);selectedId=tournaments[0].id;localStorage.removeItem(KEY);renderAll()});
  document.getElementById('tournamentModal').addEventListener('click',event=>{if(event.target.id==='tournamentModal')closeModal('tournamentModal')});

  renderAll();updateAdminUI();
})();
