(() => {
'use strict';
const ADMIN='miniamikaren@gmail.com', TKEY='bda-v3-tournaments', MKEY='bda-v3-confrontos';
let uid='copa-grifo', editId='', user=null, db=null, unsub=null, painting=false;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const admin=()=>user&&String(user.email||'').toLowerCase()===ADMIN;
function toastMsg(m){typeof toast==='function'?toast(m):console.info(m)}
function tournaments(){try{const x=JSON.parse(localStorage.getItem(TKEY));if(Array.isArray(x))return x}catch{}return[{id:'copa-grifo',name:'Copa Grifo BDA',participants:[]}]}
function store(){try{return JSON.parse(localStorage.getItem(MKEY))||{}}catch{return{}}}
function games(id=uid){return Array.isArray(store()[id])?store()[id]:[]}
function save(list){const x=store();x[uid]=list;localStorage.setItem(MKEY,JSON.stringify(x));paint();renderList();cloudSave(list)}
function tById(id){return tournaments().find(t=>t.id===id)}
function infer(){const h=$('#arenaDetail .arena-hero-copy h2')?.textContent?.trim(),t=tournaments().find(x=>x.name===h);if(t)uid=t.id;return uid}
function num(v){return v!==''&&v!=null&&!Number.isNaN(Number(v))}
function winner(g){if(g.wo==='a')return'a';if(g.wo==='b')return'b';if(!num(g.a)||!num(g.b))return'';if(+g.a>+g.b)return'a';if(+g.b>+g.a)return'b';if(num(g.pa)&&num(g.pb)){if(+g.pa>+g.pb)return'a';if(+g.pb>+g.pa)return'b'}return''}
function result(g){if(g.wo==='a')return'W.O. para '+g.ta;if(g.wo==='b')return'W.O. para '+g.tb;if(!num(g.a)||!num(g.b))return g.status||'Agendado';let r=`${+g.a} × ${+g.b}`;if(num(g.pa)&&num(g.pb))r+=` (${+g.pa}–${+g.pb} pên.)`;return r}
function meta(g){const p=[];if(g.date){const [y,m,d]=g.date.split('-');p.push(d&&m&&y?`${d}/${m}/${y}`:g.date)}if(g.time)p.push(g.time);if(g.place)p.push(g.place);return p.join(' • ')}
function order(g){const p=String(g.phase||'').toLowerCase();return p.includes('prelim')?10:p.includes('grupo')?20:p.includes('oitav')?30:p.includes('quart')?40:p.includes('semi')?50:p.includes('final')?60:25}
function sorted(){return [...games()].sort((a,b)=>order(a)-order(b)||(+a.pos||1)-(+b.pos||1)||(+a.created||0)-(+b.created||0))}
function publicHtml(){
 const list=sorted();
 if(!list.length)return '<div class="cf-empty">Nenhum confronto registrado.</div>';
 const groups={};
 list.forEach(g=>{const ph=g.phase||'Confrontos';(groups[ph]??=[]).push(g)});
 return Object.entries(groups).map(([ph,arr])=>{
  const cards=arr.map(g=>{
   const w=winner(g),m=meta(g);
   const pens=num(g.pa)&&num(g.pb)?`<div class="cf-extra">Pênaltis: ${+g.pa} × ${+g.pb}</div>`:'';
   const wo=g.wo&&g.wo!=='none'?`<div class="cf-extra">${esc(result(g))}</div>`:'';
   const note=g.note?`<p>${esc(g.note)}</p>`:'';
   return `<article class="cf-card"><div class="cf-top"><span>${esc(g.status||'Agendado')}</span><small>${esc(m)}</small></div><div class="cf-team ${w==='a'?'win':''}"><b>${esc(g.ta||'Time A')}</b><strong>${g.wo==='b'?'W.O.':num(g.a)?+g.a:'–'}</strong></div><div class="cf-team ${w==='b'?'win':''}"><b>${esc(g.tb||'Time B')}</b><strong>${g.wo==='a'?'W.O.':num(g.b)?+g.b:'–'}</strong></div>${pens}${wo}${note}</article>`;
  }).join('');
  return `<section class="cf-phase"><h3>${esc(ph)} <small>${arr.length} jogo${arr.length>1?'s':''}</small></h3><div class="cf-grid">${cards}</div></section>`;
 }).join('');
}
function paint(){if(painting)return;const d=$('#arenaDetail');if(!d)return;infer();let actions=d.querySelector('.arena-actions');if(admin()){if(!actions){actions=document.createElement('div');actions.className='arena-actions';d.querySelector('.arena-hero-copy')?.append(actions)}if(!actions.querySelector('[data-cf-open]'))actions.insertAdjacentHTML('afterbegin',`<button class="primary" type="button" data-cf-open="${esc(uid)}">Editar confrontos</button>`)}let s=$('#cfSection');if(!s){s=document.createElement('section');s.id='cfSection';s.className='cf-section';const legacy=d.querySelector('.arena-legacy');legacy?d.insertBefore(s,legacy):d.append(s)}const sig=JSON.stringify([uid,games(),!!admin()]);if(s.dataset.sig===sig)return;s.dataset.sig=sig;painting=true;s.innerHTML=`<div class="section-head"><div><span class="eyebrow">Tabela oficial</span><h2>Confrontos e resultados</h2><p>Placares, pênaltis, W.O., data, horário e local.</p></div>${admin()?`<button class="primary" data-cf-open="${esc(uid)}">Gerenciar</button>`:''}</div>${publicHtml()}`;painting=false;listen(uid)}
function teams(){const set=new Set(tById(uid)?.participants||[]);try{(JSON.parse(localStorage.getItem('bda-v2-teams'))||[]).forEach(t=>t?.name&&set.add(t.name))}catch{}return[...set].sort((a,b)=>a.localeCompare(b,'pt-BR'))}
function renderList(){const r=$('#cfList');if(!r)return;const list=sorted();r.innerHTML=list.length?list.map(g=>`<div class="cf-row"><div><b>${esc(g.phase)} • ${esc(g.ta)} ${esc(result(g))} ${esc(g.tb)}</b><span>${esc(meta(g)||g.status||'Sem data')}</span></div><div><button class="ghost" data-cf-edit="${g.id}">Editar</button><button class="danger" data-cf-del="${g.id}">Excluir</button></div></div>`).join(''):'<div class="cf-empty">Nenhum confronto. Toque em “Adicionar”.</div>'}
function open(id){if(!admin())return toastMsg('Entre como administrador');uid=id||infer();editId='';$('#cfTitle').textContent=tById(uid)?.name||'Campeonato';$('#cfModal').classList.add('show');hideForm();renderList();listen(uid)}
function close(){$('#cfModal').classList.remove('show');hideForm()}
function showForm(g){editId=g?.id||'';$('#cfForm').reset();$('#cfFormTitle').textContent=g?'Editar confronto':'Novo confronto';$('#cfStatus').value=g?.status||'Agendado';$('#cfWo').value=g?.wo||'none';$('#cfPos').value=g?.pos||1;if(g){['phase','ta','tb','a','b','pa','pb','date','time','place','note'].forEach(k=>$('#cf'+k[0].toUpperCase()+k.slice(1)).value=g[k]??'')}$('#cfTeams').innerHTML=teams().map(n=>`<option value="${esc(n)}">`).join('');$('#cfWrap').hidden=false;$('#cfPhase').focus();$('#cfWrap').scrollIntoView({behavior:'smooth'})}
function hideForm(){editId='';if($('#cfWrap'))$('#cfWrap').hidden=true}
function val(id){return $(id).value.trim()}
function nval(id){return $(id).value===''?'':+$(id).value}
function submit(e){e.preventDefault();if(!admin())return;const list=games(),old=list.find(x=>x.id===editId),now=Date.now(),g={...(old||{}),id:old?.id||`j-${now.toString(36)}-${Math.random().toString(36).slice(2,6)}`,phase:val('#cfPhase'),status:$('#cfStatus').value,ta:val('#cfTa'),tb:val('#cfTb'),a:nval('#cfA'),b:nval('#cfB'),pa:nval('#cfPa'),pb:nval('#cfPb'),wo:$('#cfWo').value,pos:+$('#cfPos').value||1,date:$('#cfDate').value,time:$('#cfTime').value,place:val('#cfPlace'),note:val('#cfNote'),created:old?.created||now,updated:now};if(g.wo!=='none'||(num(g.a)&&num(g.b)&&g.status==='Agendado'))g.status='Finalizado';old?list.splice(list.findIndex(x=>x.id===old.id),1,g):list.push(g);save(list);hideForm();toastMsg(old?'Confronto atualizado':'Confronto adicionado')}
function edit(id){const g=games().find(x=>x.id===id);if(g)showForm(g)}
function del(id){const g=games().find(x=>x.id===id);if(g&&confirm(`Excluir ${g.ta} × ${g.tb}?`)){save(games().filter(x=>x.id!==id));toastMsg('Confronto excluído')}}
function clearResult(){['#cfA','#cfB','#cfPa','#cfPb'].forEach(x=>$(x).value='');$('#cfWo').value='none';$('#cfStatus').value='Agendado'}
async function cloudSave(list){if(!db||!admin())return;try{await db.collection('arenaData').doc('confrontos-'+uid).set({dataset:'confrontos',tournamentId:uid,games:list,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:user.email.toLowerCase()})}catch(e){console.error(e);toastMsg(String(e?.code||'').includes('permission-denied')?'Publique as regras do Firestore':'Falha ao sincronizar confrontos')}}
function listen(id){if(!db||!id)return;if(unsub)unsub();unsub=db.collection('arenaData').doc('confrontos-'+id).onSnapshot(s=>{if(!s.exists)return;const data=s.data(),x=store();if(Array.isArray(data.games)&&JSON.stringify(x[id]||[])!==JSON.stringify(data.games)){x[id]=data.games;localStorage.setItem(MKEY,JSON.stringify(x));paint();renderList()}},e=>console.error(e))}
function styles(){const s=document.createElement('style');s.textContent=`.cf-section{margin-top:20px}.cf-phase{margin-top:15px}.cf-phase h3{display:flex;justify-content:space-between;color:var(--gold-soft);font:900 19px "Barlow Condensed",sans-serif;text-transform:uppercase}.cf-phase h3 small{color:var(--muted);font:800 9px sans-serif}.cf-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.cf-card{padding:12px;border:1px solid var(--line);border-radius:16px;background:linear-gradient(150deg,var(--surface-2),var(--surface))}.cf-top{display:flex;justify-content:space-between;gap:8px;color:var(--gold-soft);font-size:8px;font-weight:900;text-transform:uppercase}.cf-top small{color:var(--muted);text-align:right;text-transform:none}.cf-team{display:grid;grid-template-columns:1fr auto;align-items:center;min-height:38px;padding:7px 8px;border-top:1px solid var(--line)}.cf-team b{font-size:11px}.cf-team strong{font:900 22px "Barlow Condensed",sans-serif}.cf-team.win{border-radius:9px;background:rgba(79,223,143,.07);color:var(--green)}.cf-extra{margin-top:6px;padding:7px;border-radius:9px;color:var(--gold-soft);background:rgba(216,178,72,.08);font-size:9px;text-align:center}.cf-card p{margin:8px 0 0;color:var(--muted);font-size:9px}.cf-empty{padding:22px;border:1px dashed var(--line-strong);border-radius:16px;color:var(--muted);text-align:center}.cf-modal{width:min(720px,100%);max-height:88vh;overflow:auto}.cf-head{display:flex;justify-content:space-between;gap:12px}.cf-close{width:42px;height:42px;padding:0;border:1px solid var(--line);border-radius:12px;color:var(--text);background:#ffffff0a;font-size:20px}.cf-row{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;padding:10px;border:1px solid var(--line);border-radius:13px;background:#ffffff08}.cf-row span{display:block;margin-top:3px;color:var(--muted);font-size:9px}.cf-row>div:last-child{display:flex;gap:6px}.cf-row button{min-height:34px;padding:0 9px;font-size:9px}.cf-list{display:grid;gap:8px;margin-top:12px}.cf-wrap{margin-top:15px;padding-top:15px;border-top:1px solid var(--line)}.cf-wrap[hidden]{display:none}.cf-title{display:flex;justify-content:space-between;align-items:center}.cf-score{display:grid;grid-template-columns:1fr 76px 76px 1fr;gap:7px;align-items:end}.cf-small{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}@media(max-width:600px){.cf-grid{grid-template-columns:1fr}.cf-small{grid-template-columns:1fr}.cf-row{grid-template-columns:1fr}.cf-score{grid-template-columns:1fr 62px 62px 1fr;gap:5px}}`;document.head.append(s)}
function modal(){const m=document.createElement('div');m.id='cfModal';m.className='modal-backdrop';m.innerHTML=`<div class="modal cf-modal"><div class="cf-head"><div><span class="eyebrow">Área administrativa</span><h2 id="cfTitle">Confrontos</h2></div><button id="cfClose" class="cf-close">×</button></div><p>Edite placares, pênaltis, W.O., data, horário, local e observações.</p><button id="cfNew" class="primary" type="button">Adicionar confronto</button><div id="cfList" class="cf-list"></div><div id="cfWrap" class="cf-wrap" hidden><div class="cf-title"><h3 id="cfFormTitle">Novo confronto</h3><button id="cfHide" class="ghost" type="button">Fechar formulário</button></div><form id="cfForm"><div class="form-grid two"><label>Fase<input id="cfPhase" list="cfPhases" required placeholder="Quartas de final"><datalist id="cfPhases"><option value="Preliminar"><option value="Fase de grupos"><option value="Oitavas de final"><option value="Quartas de final"><option value="Semifinal"><option value="Final"></datalist></label><label>Status<select id="cfStatus"><option>Agendado</option><option>Em andamento</option><option>Finalizado</option><option>Adiado</option><option>Cancelado</option></select></label></div><datalist id="cfTeams"></datalist><div class="cf-score"><label>Time A<input id="cfTa" list="cfTeams" required></label><label>Gols<input id="cfA" type="number" min="0" max="99"></label><label>Gols<input id="cfB" type="number" min="0" max="99"></label><label>Time B<input id="cfTb" list="cfTeams" required></label></div><div class="form-grid two"><label>Pênaltis A<input id="cfPa" type="number" min="0" max="99"></label><label>Pênaltis B<input id="cfPb" type="number" min="0" max="99"></label><label>W.O.<select id="cfWo"><option value="none">Sem W.O.</option><option value="a">W.O. para o Time A</option><option value="b">W.O. para o Time B</option></select></label><label>Ordem na fase<input id="cfPos" type="number" min="1" max="99" value="1"></label></div><div class="cf-small"><label>Data<input id="cfDate" type="date"></label><label>Horário<input id="cfTime" type="time"></label><label>Local<input id="cfPlace" maxlength="80"></label></div><label>Observação<textarea id="cfNote" maxlength="240"></textarea></label><button id="cfClear" class="ghost" type="button">Limpar resultado</button><div class="form-actions"><button id="cfCancel" class="secondary" type="button">Cancelar</button><button class="primary" type="submit">Salvar confronto</button></div></form></div></div>`;document.body.append(m)}
function events(){document.addEventListener('click',e=>{const t=e.target.closest('[data-open-tournament],[data-home-tournament]');if(t){uid=t.dataset.openTournament||t.dataset.homeTournament||uid;setTimeout(paint)}const o=e.target.closest('[data-cf-open]');if(o)open(o.dataset.cfOpen);const ed=e.target.closest('[data-cf-edit]');if(ed)edit(ed.dataset.cfEdit);const dl=e.target.closest('[data-cf-del]');if(dl)del(dl.dataset.cfDel)});$('#cfClose').onclick=close;$('#cfModal').onclick=e=>{if(e.target.id==='cfModal')close()};$('#cfNew').onclick=()=>showForm();$('#cfHide').onclick=hideForm;$('#cfCancel').onclick=hideForm;$('#cfClear').onclick=clearResult;$('#cfForm').onsubmit=submit;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
styles();modal();events();if(window.firebase&&firebase.auth){firebase.auth().onAuthStateChanged(u=>{user=u;paint()});if(firebase.firestore){db=firebase.firestore();listen(uid)}}new MutationObserver(()=>{infer();paint()}).observe($('[data-page="tournament"]')||document.body,{childList:true,subtree:true});paint();
})();