#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

bundle() {
  local output="$1"
  shift
  local temporary="${output}.tmp"

  : > "$temporary"
  printf '/* Generated by scripts/build-production-bundles.sh. Edit the source modules, then rebuild. */\n' >> "$temporary"

  for source in "$@"; do
    printf '\n/* ===== Source: %s ===== */\n' "$source" >> "$temporary"
    sed -n '1,99999p' "$repo_dir/$source" >> "$temporary"
    printf '\n;\n' >> "$temporary"
  done

  mv "$temporary" "$output"
}

bundle "$repo_dir/arena-runtime.bundle.js" \
  arena-dom-events.js \
  arena-media-performance.js \
  team-badges.js \
  bda-logo.js

bundle "$repo_dir/arena-interface.bundle.js" \
  navegacao-arena-v2.js \
  arena-design-system.js
